version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5253:5252
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - redis
      # - splunk

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: NhonVTT-Template-redis
    ports:
      - 6379:6379
    restart: always
  # splunk:
  #   image: splunk/splunk:latest
  #   ports:
  #     - 8000:8000
  #     - 8088:8088
  #   environment:
  #     - SPLUNK_START_ARGS=--accept-license
  #     - SPLUNK_PASSWORD=Password_Here


  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - elastic

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.14.0
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - elastic

volumes:
  app_data:
