version: '3.4'

networks:
  dev:
    driver: bridge
  elastic:
    driver: bridge

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5253:5252
    environment:
      - ASPNETCORE_ENVIRONMENT=Developmenet
      - ConnectionStrings__Default=Server=postgres;Port=5432;Database=bookdb;User Id=postgres;Password=123;
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - elastic

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.14.0
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - elastic

volumes:
  app_data:
