version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5253:5252
    environment:
      - ASPNETCORE_ENVIRONMENT=Developmenet
      - ConnectionStrings__Default=Server=postgres;Port=5432;Database=bookdb;User Id=postgres;Password=123;
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
